export const types = {
    // Sync
    FILL_TASKS:   'FILL_TASKS',
    CREATE_TASK:  'CREATE_TASK',
    REMOVE_TASK:  'REMOVE_TASK:',
    UPDATE_TASK:  'UPDATE_TASK',
    SORT_TASKS:   'SORT_TASKS',
    FILTER_TASKS: 'FILTER_TASKS',

    // Async
    FETCH_TASKS_ASYNC: 'FETCH_TASKS_ASYNC',
    CREATE_TASK_ASYNC: 'CREATE_TASK_ASYNC',
    REMOVE_TASK_ASYNC: 'REMOVE_TASK_ASYNC',
    UPDATE_TASK_ASYNC: 'UPDATE_TASK_ASYNC',
};
